//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SocialPuentes.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Db_CPuentesEntities : DbContext
    {
        public Db_CPuentesEntities()
            : base("name=Db_CPuentesEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Cede> Cedes { get; set; }
        public virtual DbSet<Comentario> Comentarios { get; set; }
        public virtual DbSet<Especialidade> Especialidades { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<Sugerencia> Sugerencias { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<Valoracione> Valoraciones { get; set; }
        public virtual DbSet<Modulo> Modulos { get; set; }
        public virtual DbSet<Publicacione> Publicaciones { get; set; }
        public virtual DbSet<Usuario> Usuarios { get; set; }
    }
}
