//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SocialPuentes.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Publicacione
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Publicacione()
        {
            this.Comentarios = new HashSet<Comentario>();
            this.Valoraciones = new HashSet<Valoracione>();
        }
    
        public int Id_Publicacion { get; set; }
        public int Id_Usuario { get; set; }
        public string Nombre_Usuario { get; set; }
        public string Tema { get; set; }
        public int Id_Modulos { get; set; }
        public string Publicacion { get; set; }
        public byte[] URL_Imagen { get; set; }
        public string URL_Archivo { get; set; }
        public Nullable<System.DateTime> Fecha_Publicacion { get; set; }
        public Nullable<bool> Estado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Comentario> Comentarios { get; set; }
        public virtual Modulo Modulo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Valoracione> Valoraciones { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
