//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SocialPuentes.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Valoracione
    {
        public int Id_Valoracion { get; set; }
        public int Id_Usuario { get; set; }
        public string Nombre_Usuario { get; set; }
        public int Id_Publicacion { get; set; }
        public Nullable<int> Valoracion { get; set; }
    
        public virtual Publicacione Publicacione { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
